import type { DecisionMemo, EvidenceClaim, UnknownMetric } from './evidence';
import type { FactConcept, FounderFact } from './founder-facts';
import type { PathwaysResult } from './hippo/types';
export type Sector = 'Quick Commerce' | 'D2C / Consumer' | 'B2B SaaS' | 'Digital Agency' | 'Fintech' | 'Healthtech' | 'Edtech' | 'Marketplace' | 'Manufacturing' | 'Other';
export type ReportLanguage = 'Simple English' | 'Hinglish';

export type Provenance = 'FOUNDER_STATED' | 'CALCULATED' | 'EXTERNAL' | 'ASSUMPTION' | 'HYPOTHESIS';
export type RowTimeframe = 'CURRENT' | 'TARGET' | 'PROPOSED' | 'CONDITIONAL' | 'PROJECTION' | 'ASSUMPTION';
export type RowConcept = FactConcept | 'contribution' | 'cac' | 'payback';
export type UnitEconomicsRow = {
  metric: string; conservative: number; base: number; upside: number; unit: string; commentary: string; assumption: string;
  // Provenance (optional so older stored reports stay valid)
  concept?: RowConcept; timeframe?: RowTimeframe; provenance?: Provenance; factId?: string; inputs?: string[]; basis?: string; differsFromFounder?: boolean;
};

export type AuditReport = {
  executiveSummary: string;
  score: number;
  verdict: string;
  oneLineVerdict: string;
  whatThisBusinessIs: string;
  whyItCouldWork: string[];
  whatMustBeTrue: string[];
  customer: { icp: string; problem: string; willingnessToPay: string };
  businessModel: { revenueModel: string; pricingLogic: string; keyCostDrivers: string[] };
  marketView: { marketType: string; demandSignal: string; competition: string; marketRisk: string };
  unitEconomics: UnitEconomicsRow[];
  experiments: { hypothesis: string; test: string; metric: string; passThreshold: string; failThreshold: string }[];
  operatingModel: string[];
  technologyBuild: { mvp: string[]; avoidBuilding: string[]; estimatedBuildApproach: string };
  regulatory: { name: string; status: 'Likely' | 'Conditional' | 'Low signal'; rationale: string; action: string; source: string; trigger?: string; activity?: string; requirement?: string; sourceIds?: string[] }[];
  unknownEconomics?: UnknownMetric[];
  // Evidence layer (optional: older stored reports do not have these)
  decisionMemo?: DecisionMemo;
  /** 3–5 alternative pathways, generated by the audit job after the decision memo (absent on older reports). */
  pathways?: PathwaysResult;
  claimProvenance?: Partial<Record<import('./claim-provenance').NarrativeField, import('./claim-provenance').ClaimProvenance>>;
  evidence?: EvidenceClaim[];
  vulnerabilities: { risk: string; probability: 'Low' | 'Medium' | 'High'; impact: 'Low' | 'Medium' | 'High'; whyItMatters: string; mitigation: string }[];
  goToMarket: string[];
  thirtyDayPlan: { week: string; objective: string; actions: string[]; successMetric: string }[];
  killOrScale: { scaleWhen: string[]; pauseWhen: string[] };
  assumptions: string[];
  nextSteps: string[];
};

const isHinglish = (language: ReportLanguage) => language === 'Hinglish';

/**
 * Structural skeleton of a report (founder facts only, no invented numbers, no research).
 * NEVER returned to a founder as an audit: the engine has no template path. Used as a test fixture and
 * as the shape reference for report validation.
 */
export function deterministicAudit(input: { idea: string; sector: Sector; stage?: string; geography?: string; language?: ReportLanguage; scope?: string; founderFacts?: FounderFact[] }): AuditReport {
  const t = input.idea.toLowerCase();
  const lang = input.language || 'Simple English';
  const physical = ['Quick Commerce','D2C / Consumer','Manufacturing'].includes(input.sector) || /(store|warehouse|food|device|electronics|product|manufactur|inventory|delivery)/.test(t);
  const data = ['B2B SaaS','Digital Agency','Fintech','Healthtech','Edtech','Marketplace','Quick Commerce','D2C / Consumer'].includes(input.sector) || /(app|platform|saas|customer data|personal data|users|whatsapp|payment)/.test(t);
  const money = input.sector === 'Fintech' || /(loan|lending|credit|wallet|payment|insurance|investment|nidhi|nbfc)/.test(t);
  const bis = input.sector === 'Manufacturing' || /(electronics|charger|toy|helmet|appliance|battery|steel|cement|device)/.test(t);
  const subscription = ['B2B SaaS','Digital Agency'].includes(input.sector);
  const score = Math.max(38, Math.min(86, 67 + (input.sector === 'B2B SaaS' ? 8 : 0) - (money ? 9 : 0) - (physical ? 4 : 0)));

  const simple = isHinglish(lang);
  const verdict = score >= 75 ? (simple ? 'Idea mein potential hai, but pehle small paid pilot se proof chahiye.' : 'Promising, but prove demand and economics before scaling.') : score >= 58 ? (simple ? 'Potential hai, lekin kuch critical assumptions abhi prove nahi hue hain.' : 'Potentially viable, but several critical assumptions need proof.') : (simple ? 'Abhi uncertainty high hai. Pehle core demand validate karo.' : 'Uncertainty is high. Validate the core demand before investing heavily.');

  const regulatory = [
    { name: 'GST', status: 'Likely' as const, rationale: simple ? 'Business mein taxable sales/services ho sakti hain. GST registration turnover, supply type aur exceptions par depend karega.' : 'GST registration and invoicing depend on taxable supplies, turnover, supply type and applicable exceptions.', action: simple ? 'Expected turnover, states, taxable supplies aur inter-state/e-commerce flows map karke CA se confirm karein.' : 'Map expected turnover, states, taxable supplies and inter-state/e-commerce flows with a tax professional.', source: 'https://cbic-gst.gov.in/faq.html' },
    { name: 'MSME / Udyam', status: 'Likely' as const, rationale: simple ? 'Indian operating business ke liye Udyam eligibility check karna useful hai; registration government portal par free hai.' : 'An Indian operating business should assess Udyam eligibility; registration is available through the government portal.', action: simple ? 'Current investment aur turnover classification check karke official Udyam portal use karein.' : 'Check current investment and turnover classification and use the official Udyam portal.', source: 'https://www.udyamregistration.gov.in/' },
    { name: 'BIS', status: bis ? 'Likely' as const : 'Conditional' as const, rationale: bis ? 'Product category compulsory certification/QCO regime mein aa sakti hai.' : 'BIS is product-specific and becomes mandatory where a government order/QCO applies.', action: simple ? 'Exact SKU/category identify karke current BIS compulsory lists check karein.' : 'Identify the exact SKU/category and check the current BIS compulsory-certification/QCO lists.', source: 'https://www.bis.gov.in/product-certification/products-under-compulsory-certification/' },
    { name: 'DPDP', status: data ? 'Likely' as const : 'Conditional' as const, rationale: data ? 'Business likely digital personal data process karega, so privacy controls launch se pehle design karne honge.' : 'Applicability depends on whether and how the business processes digital personal data.', action: simple ? 'Data map karein: kya collect kar rahe hain, kyun, kitne time ke liye, kiske saath share hota hai.' : 'Map personal-data flows, purpose, notices, lawful basis, processor contracts, retention and user-rights workflows.', source: 'https://www.meity.gov.in/static/uploads/2024/02/Digital-Personal-Data-Protection-Act-2023.pdf' },
    { name: 'Sector licensing', status: money ? 'Likely' as const : 'Conditional' as const, rationale: money ? 'Idea regulated financial activity ko touch karta hai.' : 'No specific sector licence is inferred from the intake alone.', action: money ? 'Exact regulated activity define karke RBI/IRDAI/SEBI or relevant framework validate karein.' : 'Confirm sector and state-specific rules before launch.', source: 'https://www.rbi.org.in/' }
  ];

  const facts = (input.founderFacts || []).filter((f) => f.locked && f.confirmedByFounder);
  // No sector defaults: numbers exist only if the founder stated them (rows inserted by report validation)
  // or they are calculated from founder facts.
  const unitEconomics: UnitEconomicsRow[] = [];
  const fPrice = facts.find((f) => f.concept === 'selling_price' && f.value !== undefined && f.timeframe !== 'TARGET');
  const fCost = facts.find((f) => f.concept === 'unit_cost' && f.value !== undefined && f.timeframe !== 'TARGET');
  if (fPrice && fCost && !fPrice.period && fPrice.unit === fCost.unit) {
    const c = Math.round((fPrice.value! - fCost.value!) * 100) / 100;
    unitEconomics.unshift({ metric: 'Contribution per unit (price − cost)', conservative: c, base: c, upside: c, unit: '₹ / unit', commentary: 'Founder price minus founder cost, before shipping, marketing and other variable costs.', assumption: `CALCULATED from ${fPrice.id} and ${fCost.id}.`, concept: 'contribution', timeframe: 'CURRENT', provenance: 'CALCULATED', inputs: [fPrice.id, fCost.id] });
  }

  const vulnerabilities = [
    { risk: 'Demand validation', probability: 'High' as const, impact: 'High' as const, whyItMatters: simple ? 'Idea achha lagna aur customer ka paisa dena alag cheez hai.' : 'Interest is not the same as willingness to pay.', mitigation: simple ? '10–20 target customers ke saath paid/manual pilot run karein.' : 'Run a paid or commitment-based pilot with 10–20 target customers.' },
    { risk: 'Unit economics', probability: 'High' as const, impact: 'High' as const, whyItMatters: simple ? 'Scale karne par loss bhi scale ho sakta hai.' : 'Scaling can amplify losses if contribution is weak.', mitigation: simple ? 'CAC, gross contribution, fulfilment/service cost aur payback daily/weekly track karein.' : 'Track CAC, gross contribution, service/fulfilment cost and payback from the first customers.' },
    { risk: 'Regulatory interpretation', probability: money || bis ? 'High' as const : 'Medium' as const, impact: 'High' as const, whyItMatters: simple ? 'Wrong structure se launch delay ya compliance cost aa sakti hai.' : 'Incorrect assumptions can create launch delays or compliance cost.', mitigation: simple ? 'Exact activity map karke specialist CA/lawyer/compliance advisor se validate karein.' : 'Map the exact activity and validate with a relevant professional before launch.' },
    { risk: 'Execution bandwidth', probability: 'High' as const, impact: 'Medium' as const, whyItMatters: simple ? 'Too many features se founder ka focus toot sakta hai.' : 'Too many features can dilute founder focus.', mitigation: simple ? 'One ICP, one wedge, one core workflow aur one 30-day metric rakhein.' : 'Choose one ICP, one wedge, one core workflow and one 30-day metric.' },
    { risk: 'Platform / channel dependency', probability: data ? 'Medium' as const : 'Low' as const, impact: 'Medium' as const, whyItMatters: simple ? 'WhatsApp, marketplaces ya APIs ke rules badal sakte hain.' : 'Third-party platform or API changes can affect distribution or operations.', mitigation: simple ? 'Data, source code aur customer relationship portable rakhein; single-channel dependency avoid karein.' : 'Keep code, data and customer relationships portable; avoid single-channel dependency.' }
  ];

  // 5 generic fallback experiments — sector-agnostic, applicable to any business idea
  const experiments = [
    {
      hypothesis: 'The target customer has a painful enough problem that they will pay for a solution before it is fully built.',
      test: 'Describe the proposed solution to 10 target customers and ask for a deposit or signed commitment — not just interest.',
      metric: 'Number of customers who pay a deposit or sign a commitment letter out of 10 approached.',
      passThreshold: '3 or more customers pay or commit within 2 weeks.',
      failThreshold: 'Fewer than 2 customers are willing to pay or commit after 10 conversations.',
    },
    {
      hypothesis: 'The proposed price is within the range the target customer considers acceptable given their current alternatives.',
      test: 'Present the price explicitly in 10 sales conversations. Record objections, counter-offers and drop-offs.',
      metric: 'Percentage of conversations where price is not raised as a blocking objection.',
      passThreshold: '60% or more of conversations proceed past the price disclosure without a blocking objection.',
      failThreshold: 'More than 50% of conversations stall or end when the price is stated.',
    },
    {
      hypothesis: 'The core workflow can be delivered manually at acceptable quality before any software is built.',
      test: 'Run a concierge pilot: deliver the core outcome manually for 3–5 paying customers using existing tools (spreadsheets, WhatsApp, phone).',
      metric: 'Customer satisfaction score and repeat usage rate after the manual pilot.',
      passThreshold: 'At least 3 of 5 pilot customers say they would use the service again and rate it 7/10 or higher.',
      failThreshold: 'Fewer than 2 customers would repeat or satisfaction is below 5/10 on average.',
    },
    {
      hypothesis: 'The unit economics are viable: gross contribution per customer exceeds variable cost at the stated price.',
      test: 'Track actual revenue, direct variable cost (delivery, fulfilment, messaging, support time) and acquisition cost for the first 5 customers.',
      metric: 'Gross contribution per customer after direct variable costs.',
      passThreshold: 'Gross contribution is positive for at least 4 of 5 customers; CAC payback is under 6 months at base case.',
      failThreshold: 'Gross contribution is negative for 2 or more customers, or CAC payback exceeds 12 months.',
    },
    {
      hypothesis: 'At least one repeatable customer acquisition channel exists that does not rely solely on the founder\'s personal network.',
      test: 'Run one outbound acquisition experiment (cold outreach, a paid ad, a referral programme, or a partner channel) targeting 20 prospects outside the founder\'s existing contacts.',
      metric: 'Conversion rate from cold prospect to paying customer through the tested channel.',
      passThreshold: 'At least 2 of 20 cold prospects convert to paying customers within 30 days.',
      failThreshold: 'Zero conversions from 20 cold prospects after 30 days of consistent effort.',
    },
  ];

  return {
    executiveSummary: simple
      ? `Bottom line: ${verdict} ${input.sector} mein biggest question demand + unit economics hai. Aristotle ke current assumptions ke hisaab se score ${score}/100 hai. Is score ko investment decision na samjhein; yeh screening signal hai.`
      : `Bottom line: ${verdict} The core question is whether customers will pay at a price that leaves enough contribution after variable cost and acquisition. Aristotle's current screening score is ${score}/100; it is a decision aid, not an investment recommendation.`,
    score,
    verdict,
    oneLineVerdict: simple ? `${verdict} Pehle proof, phir scale.` : `${verdict} Prove first, then scale.`,
    whatThisBusinessIs: simple ? `Aapka idea ${input.sector} business hai jo ${input.idea.slice(0, 220)}${input.idea.length > 220 ? '…' : ''}` : `This is a ${input.sector} business built around: ${input.idea.slice(0, 260)}${input.idea.length > 260 ? '…' : ''}`,
    whyItCouldWork: [
      simple ? 'Customer ki problem clear aur frequent honi chahiye.' : 'The problem should be frequent, painful and easy for the customer to recognise.',
      simple ? 'Narrow ICP ke saath sales story simple ho sakti hai.' : 'A narrow ICP can make the sales proposition much easier to prove.',
      simple ? 'Agar repeat usage aata hai to economics improve ho sakti hai.' : 'Repeat usage can improve economics and create operating leverage.'
    ],
    whatMustBeTrue: [
      simple ? 'Target customer real problem ke liye pay kare.' : 'The target customer must pay for the problem being solved.',
      simple ? 'Variable cost ke baad healthy contribution bache.' : 'Contribution after variable costs must be positive and improve with scale.',
      simple ? 'Acquisition channel repeatable ho.' : 'At least one customer-acquisition channel must become repeatable.',
      simple ? 'Operational complexity revenue ke saath control mein rahe.' : 'Operational complexity must not grow faster than revenue.'
    ],
    customer: {
      icp: simple ? `Start with one sharply defined customer group in ${input.geography || 'India'}.` : `Start with one sharply defined customer group in ${input.geography || 'India'}.`,
      problem: simple ? 'Customer ka current workaround kya hai, aur usmein kitna time/paisa/risk waste hota hai — this must be proven.' : 'Prove the current workaround, its cost and why the customer would switch.',
      willingnessToPay: simple ? 'Interview se zyada useful paid pilot, deposit ya signed commitment hai.' : 'A paid pilot, deposit or signed commitment is stronger evidence than interview enthusiasm.'
    },
    businessModel: {
      revenueModel: subscription ? (input.sector === 'B2B SaaS' ? 'Recurring SaaS subscription' : 'Project/retainer fee') : 'Transaction or product-linked revenue',
      pricingLogic: simple ? 'Price ko customer value + competitor benchmark + gross contribution ke against test karein.' : 'Test price against customer value, competitor alternatives and required gross contribution.',
      keyCostDrivers: physical ? ['Inventory / procurement', 'Fulfilment / delivery', 'Returns / wastage', 'Customer acquisition'] : ['People / delivery cost', 'Cloud / software', 'Customer acquisition', 'Support / operations']
    },
    marketView: {
      marketType: subscription ? 'Recurring B2B / professional service' : physical ? 'Operationally intensive consumer market' : 'Digital / service-led market',
      demandSignal: simple ? 'Strongest signal = customer actually pays or commits.' : 'The strongest early demand signal is payment or a credible commercial commitment.',
      competition: simple ? 'Competition ko features se nahi, customer ke current alternative se compare karein.' : "Compare against the customer's current alternative, not only direct feature competitors.",
      marketRisk: simple ? 'Top-down TAM se zyada important hai first 100 customers ka reachable market.' : 'Reachable demand among the first 100 customers matters more than a large top-down TAM.'
    },
    unitEconomics,
    experiments,
    operatingModel: [
      simple ? 'Founder-led sales and customer discovery first.' : 'Founder-led sales and customer discovery first.',
      simple ? 'Manual/concierge workflow se repeatability prove karein.' : 'Use a manual or concierge workflow before automating the full process.',
      simple ? 'Only bottlenecks automate karein; everything build mat karein.' : 'Automate bottlenecks only; do not build the entire workflow upfront.'
    ],
    technologyBuild: {
      mvp: ['Landing page + lead capture', 'Core workflow for one use case', 'Basic analytics and customer feedback', 'Payment/invoicing where needed', 'Exportable customer/data records'],
      avoidBuilding: ['Complex admin panels before demand', 'Large mobile apps before repeat usage', 'Custom AI models without proven volume', 'Multi-city/multi-segment workflows on day one'],
      estimatedBuildApproach: simple ? 'Start with no-code/manual operations where possible; build only the workflow that customers repeatedly use.' : 'Start with manual/no-code operations where possible; build only the workflow customers repeatedly use.'
    },
    // Only regulation triggered by this business model; nothing is listed "by default".
    regulatory: regulatory
      .filter((r) => r.name === 'GST' || (r.name === 'BIS' && bis) || (r.name === 'DPDP' && data) || (r.name === 'Sector licensing' && money))
      .map((r) => ({ ...r, status: r.name === 'GST' ? ('Conditional' as const) : r.status, trigger: r.name === 'GST' ? 'Taxable sales of goods or services (registration depends on turnover and supply type)' : r.name === 'BIS' ? 'Selling a product category that may be under a BIS quality control order' : r.name === 'DPDP' ? 'Collecting and processing customers’ digital personal data' : 'Handling money, credit, payments or insurance for customers' })),
    // Template fallback (Demo Mode only): no research was done, so every critical assumption is UNKNOWN.
    decisionMemo: {
      decisionQuestion: `Is there enough evidence to invest more time and money in this ${input.sector} business?`,
      criticalAssumptions: [
        { assumption: 'The target customer has this problem often enough to pay to solve it.', whyItMatters: 'Without a painful, frequent problem there is no business.', evidenceStatus: 'UNKNOWN' as const, evidence: 'No research was performed for this report.', evidenceIds: [], cheapestTest: 'Ask 10 target customers for a deposit or signed commitment.', experimentIndex: 1 },
        { assumption: 'Customers will accept the price you plan to charge.', whyItMatters: 'Price sets whether each sale makes or loses money.', evidenceStatus: 'UNKNOWN' as const, evidence: 'No research was performed for this report.', evidenceIds: [], cheapestTest: 'State the price in 10 sales conversations and record objections.', experimentIndex: 2 },
        { assumption: 'Each customer earns more than it costs to win and serve them.', whyItMatters: 'Growth multiplies losses if unit economics are negative.', evidenceStatus: 'UNKNOWN' as const, evidence: 'No research was performed for this report.', evidenceIds: [], cheapestTest: 'Track revenue, variable cost and acquisition cost for the first 5 customers.', experimentIndex: 4 },
      ],
      proceedIf: ['At least 3 of 10 target customers pay or commit.', 'Contribution per customer is positive after variable costs.'],
      changeModelIf: ['Customers like the idea but will not pay.', 'Acquisition cost repeatedly exceeds contribution per customer.'],
      evidenceStillRequired: ['Real customer willingness to pay', 'Actual variable cost per customer', 'A repeatable acquisition channel'],
    },
    evidence: [
      { claim: 'All market, customer and economics statements in this report are template assumptions, not researched facts.', type: 'ASSUMPTION' as const, sourceIds: [], confidence: 'LOW' as const, validation: 'Run the experiments in section 9.' },
    ],
    vulnerabilities,
    goToMarket: [
      simple ? 'One ICP choose karein; everyone ko target mat karein.' : 'Choose one ICP; do not target everyone.',
      simple ? '10–20 customer interviews → 5 paid pilots → repeat usage.' : '10–20 interviews → 5 paid pilots → repeat usage.',
      simple ? 'Founder-led outbound + referrals se first customers laayein.' : 'Use founder-led outbound and referrals for the first customers.',
      simple ? 'Pilot data ke basis par pricing aur product change karein.' : 'Use pilot data to refine pricing and product before scaling acquisition.'
    ],
    thirtyDayPlan: [
      { week: 'Week 1', objective: 'Problem proof', actions: ['Interview 15 target customers', 'Document current workaround and spend', 'Write one clear paid offer'], successMetric: '15 interviews + at least 5 strong problem confirmations' },
      { week: 'Week 2', objective: 'Willingness to pay', actions: ['Pitch the offer', 'Ask for payment/deposit/commitment', 'Manually deliver the core outcome'], successMetric: 'At least 3–5 paid or committed pilots' },
      { week: 'Week 3', objective: 'Economics proof', actions: ['Measure revenue, variable cost, time-to-serve and CAC', 'Remove low-value steps', 'Test one pricing change'], successMetric: 'Known contribution per customer and first CAC benchmark' },
      { week: 'Week 4', objective: 'Scale decision', actions: ['Review repeat usage', 'Choose the one acquisition channel that worked', 'Define the smallest build backlog'], successMetric: 'Clear scale/pause decision backed by customer data' }
    ],
    killOrScale: {
      scaleWhen: simple ? ['Customers pay without heavy discounting.', 'Repeat usage/renewal is visible.', 'Contribution after variable cost is positive.', 'One acquisition channel shows repeatability.'] : ['Customers pay without heavy discounting.', 'Repeat usage or renewal is visible.', 'Contribution after variable cost is positive.', 'At least one acquisition channel is repeatable.'],
      pauseWhen: simple ? ['Customers like the idea but refuse to pay.', 'CAC repeatedly exceeds expected contribution.', 'Operational effort grows faster than revenue.', 'A key regulatory dependency cannot be solved economically.'] : ['Customers like the idea but will not pay.', 'CAC repeatedly exceeds expected contribution.', 'Operational effort grows faster than revenue.', 'A key regulatory dependency cannot be solved economically.']
    },
    assumptions: [
      'These economics are scenario estimates, not market-verified quotes.',
      `Geography assumed: ${input.geography || 'India'}.`,
      `Stage assumed: ${input.stage || 'Idea / pre-launch'}.`,
      'Regulatory items are screening prompts, not legal or tax advice.',
      ...(input.scope === 'GROWTH_PLAN' ? ['Scope: existing business (Growth Plan). Founder-stated current numbers are the baseline.'] : []),
      ...(facts.length ? ['Founder-stated numbers are LOCKED and used exactly as confirmed; sector defaults are never substituted for them.'] : [])
    ],
    nextSteps: [
      simple ? 'Aaj: one ICP + one paid offer finalise karein.' : 'Today: finalise one ICP and one paid offer.',
      simple ? 'Next 7 days: 15 customer conversations + 3 paid pilot attempts.' : 'Next 7 days: 15 customer conversations and 3 paid-pilot attempts.',
      simple ? 'Next 14 days: actual CAC, contribution aur repeat usage measure karein.' : 'Next 14 days: measure actual CAC, contribution and repeat usage.',
      simple ? 'Day 30: scale ya pause ka decision actual data par lein.' : 'Day 30: make the scale-or-pause decision using actual evidence.'
    ]
  };
}
