import { notFound } from 'next/navigation';
import { ArrowDownToLine, CheckCircle2, ExternalLink, ShieldAlert, Target, TrendingUp, TriangleAlert, Wrench } from 'lucide-react';
import { db } from '@/lib/db';
import { getCurrentUser } from '@/lib/session';
import { AuditReport, deterministicAudit } from '@/lib/audit';

const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`;

export default async function AuditPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const user=await getCurrentUser();
 if(!user)return <main className="mx-auto max-w-4xl px-6 py-20"><h1 className="text-3xl font-semibold">Session required</h1><p className="mt-3 text-[#93a0b5]">Open this audit in the same browser session used to submit it.</p></main>;
 const audit=await db.audit.findFirst({where:{id,userId:user.id}}); if(!audit)return notFound();
 if(audit.status!=='completed')return <main className="mx-auto max-w-4xl px-6 py-20"><h1 className="text-3xl font-semibold">Audit processing</h1><p className="mt-3 text-[#93a0b5]">This audit has not completed yet.</p></main>;
 const raw=JSON.parse(audit.report) as Partial<AuditReport>; const base=deterministicAudit({idea:audit.idea,sector:audit.sector as any,stage:audit.stage||undefined,geography:audit.geography||'India',language:(audit.reportLanguage as any)||'Simple English'}); const r={...base,...raw,customer:raw.customer||base.customer,businessModel:raw.businessModel||base.businessModel,marketView:raw.marketView||base.marketView,technologyBuild:raw.technologyBuild||base.technologyBuild,killOrScale:raw.killOrScale||base.killOrScale} as AuditReport;
 return <main className="mx-auto max-w-6xl px-6 py-10 pb-20">
  <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="text-xs uppercase tracking-[.2em] text-[#77e2c1]">ARISTOTLE · FOUNDER DECISION MEMO · {audit.sector}</div><h1 className="mt-3 max-w-4xl text-4xl font-semibold tracking-tight md:text-5xl">{audit.idea}</h1><p className="mt-3 text-sm text-[#7f8da3]">Prepared {audit.createdAt.toLocaleString('en-IN')} · {audit.reportLanguage}</p></div><a href={`/api/audits/${audit.id}/export`} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#3a4657] px-4 py-3 font-medium hover:border-[#77e2c1]"><ArrowDownToLine size={17}/> Lock-and-Barrel Export</a></div>

  <section className="mt-8 rounded-3xl border border-[#263446] bg-[#0d121a] p-7 md:p-9"><div className="grid gap-8 md:grid-cols-[1.5fr_.5fr] md:items-center"><div><div className="text-xs font-semibold uppercase tracking-[.18em] text-[#77e2c1]">THE ANSWER IN 60 SECONDS</div><h2 className="mt-3 text-2xl font-semibold md:text-3xl">{r.oneLineVerdict}</h2><p className="mt-5 max-w-3xl text-[15px] leading-7 text-[#c2cad6]">{r.executiveSummary}</p></div><div className="rounded-2xl border border-[#2a394b] bg-[#0a0f16] p-5 text-center"><div className="text-xs uppercase tracking-wider text-[#7f8da3]">Screening score</div><div className="mt-2 text-6xl font-semibold text-[#77e2c1]">{Math.round(r.score)}<span className="text-2xl text-[#536176]">/100</span></div><div className="mt-2 text-xs leading-5 text-[#718096]">A screening signal, not an investment recommendation.</div></div></div></section>

  <div className="mt-4 grid gap-4 md:grid-cols-3">
   <InfoCard icon={<Target size={18}/>} title="What this business is" text={r.whatThisBusinessIs}/>
   <InfoCard icon={<TrendingUp size={18}/>} title="Why it could work" items={r.whyItCouldWork}/>
   <InfoCard icon={<TriangleAlert size={18}/>} title="What must be true" items={r.whatMustBeTrue}/>
  </div>

  <Section title="1. Customer & problem"><div className="grid gap-4 md:grid-cols-3"><Mini title="Ideal customer" text={r.customer.icp}/><Mini title="Problem to prove" text={r.customer.problem}/><Mini title="Willingness to pay" text={r.customer.willingnessToPay}/></div></Section>
  <Section title="2. Business model & market"><div className="grid gap-4 md:grid-cols-2"><Mini title="Revenue model" text={r.businessModel.revenueModel}/><Mini title="Pricing logic" text={r.businessModel.pricingLogic}/><Mini title="Market view" text={r.marketView.marketType}/><Mini title="Competition" text={r.marketView.competition}/></div><div className="mt-4 rounded-2xl border border-[#202938] bg-[#0a0f16] p-5"><div className="text-xs uppercase tracking-wider text-[#718096]">Key cost drivers</div><ul className="mt-3 grid gap-2 md:grid-cols-2">{r.businessModel.keyCostDrivers.map(x=><li key={x} className="flex gap-2 text-sm text-[#c0c8d5]"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-[#77e2c1]"/>{x}</li>)}</ul></div></Section>

  <Section title="3. Unit economics"><p className="mb-5 text-sm text-[#7f8da3]">These are scenario estimates. Replace them with real pilot data before making a scale decision.</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-[#718096]"><tr><th className="pb-3">Metric</th><th className="pb-3">Conservative</th><th className="pb-3">Base</th><th className="pb-3">Upside</th><th className="pb-3">Read this as</th></tr></thead><tbody>{r.unitEconomics.map(x=><tr key={x.metric} className="border-t border-[#202938]"><td className="py-4 pr-4 font-medium">{x.metric}<div className="text-xs font-normal text-[#536176]">{x.unit}</div></td><td className="py-4">{money(x.conservative)}</td><td className="py-4">{money(x.base)}</td><td className="py-4">{money(x.upside)}</td><td className="max-w-sm py-4 text-xs leading-5 text-[#8e9bae]">{x.commentary}</td></tr>)}</tbody></table></div></Section>

  <Section title="4. How to build it"><div className="grid gap-4 md:grid-cols-3"><Mini title="MVP — build first" items={r.technologyBuild.mvp}/><Mini title="Do not build yet" items={r.technologyBuild.avoidBuilding}/><Mini title="Operating model" items={r.operatingModel}/></div><div className="mt-4 rounded-2xl border border-[#202938] bg-[#0a0f16] p-5"><div className="text-xs uppercase tracking-wider text-[#718096]">Build principle</div><p className="mt-2 text-sm leading-6 text-[#c0c8d5]">{r.technologyBuild.estimatedBuildApproach}</p></div></Section>

  <Section title="5. India regulatory radar"><div className="grid gap-3 md:grid-cols-2">{r.regulatory.map(x=><div key={x.name} className="rounded-2xl border border-[#202938] bg-[#0a0f16] p-5"><div className="flex items-center justify-between"><div className="font-medium">{x.name}</div><span className="rounded-full border border-[#2d3b4c] px-2.5 py-1 text-xs text-[#77e2c1]">{x.status}</span></div><p className="mt-3 text-sm leading-6 text-[#a0adbf]">{x.rationale}</p><p className="mt-3 text-sm leading-6 text-[#d1d7e0]"><strong>Do this:</strong> {x.action}</p><a className="mt-4 inline-flex items-center gap-1 text-xs text-[#77e2c1]" href={x.source} target="_blank" rel="noreferrer">Official source <ExternalLink size={12}/></a></div>)}</div></Section>

  <Section title="6. Vulnerability matrix"><div className="space-y-3">{r.vulnerabilities.map(x=><div key={x.risk} className="grid gap-4 rounded-2xl border border-[#202938] bg-[#0a0f16] p-5 md:grid-cols-[1.1fr_.35fr_1.6fr]"><div><div className="font-medium">{x.risk}</div><p className="mt-2 text-sm leading-6 text-[#8e9bae]">{x.whyItMatters}</p></div><div className="text-xs leading-6 text-[#ffcf70]">{x.probability} probability<br/>{x.impact} impact</div><div className="text-sm leading-6 text-[#c0c8d5]"><strong>Mitigation:</strong> {x.mitigation}</div></div>)}</div></Section>

  <Section title="7. Go-to-market"><ol className="grid gap-3 md:grid-cols-2">{r.goToMarket.map((x,i)=><li key={x} className="flex gap-4 rounded-2xl border border-[#202938] bg-[#0a0f16] p-5"><span className="text-sm font-semibold text-[#77e2c1]">0{i+1}</span><span className="text-sm leading-6 text-[#c0c8d5]">{x}</span></li>)}</ol></Section>

  <Section title="8. The first 30 days"><div className="grid gap-3 md:grid-cols-4">{r.thirtyDayPlan.map(x=><div key={x.week} className="rounded-2xl border border-[#202938] bg-[#0a0f16] p-5"><div className="text-xs font-semibold uppercase tracking-wider text-[#77e2c1]">{x.week}</div><h3 className="mt-3 font-medium">{x.objective}</h3><ul className="mt-4 space-y-2 text-sm leading-5 text-[#9aa7ba]">{x.actions.map(a=><li key={a}>• {a}</li>)}</ul><div className="mt-5 border-t border-[#202938] pt-3 text-xs leading-5 text-[#c0c8d5]"><strong>Success:</strong> {x.successMetric}</div></div>)}</div></Section>

  <div className="mt-4 grid gap-4 md:grid-cols-2"><Section title="Scale when"><ul className="space-y-3">{r.killOrScale.scaleWhen.map(x=><li key={x} className="flex gap-2 text-sm leading-6 text-[#c0c8d5]"><CheckCircle2 size={16} className="mt-1 shrink-0 text-[#77e2c1]"/>{x}</li>)}</ul></Section><Section title="Pause / rethink when"><ul className="space-y-3">{r.killOrScale.pauseWhen.map(x=><li key={x} className="flex gap-2 text-sm leading-6 text-[#c0c8d5]"><TriangleAlert size={16} className="mt-1 shrink-0 text-[#ffcf70]"/>{x}</li>)}</ul></Section></div>

  <div className="mt-4 grid gap-4 md:grid-cols-2"><Section title="Immediate next steps"><ul className="space-y-3">{r.nextSteps.map(x=><li key={x} className="flex gap-2 text-sm leading-6 text-[#c0c8d5]"><CheckCircle2 size={16} className="mt-1 shrink-0 text-[#77e2c1]"/>{x}</li>)}</ul></Section><Section title="Assumptions"><ul className="space-y-3">{r.assumptions.map(x=><li key={x} className="text-sm leading-6 text-[#8e9bae]">• {x}</li>)}</ul></Section></div>

  <div className="mt-6 grid gap-4 md:grid-cols-[1fr_.8fr]"><div className="rounded-2xl border border-[#6b4d17] bg-[#1a1408] p-5 text-sm leading-6 text-[#d6bd83]"><ShieldAlert size={18} className="mb-2"/>Regulatory screening is not legal or tax advice. Requirements can change and may depend on facts not captured by the intake.</div><div className="rounded-2xl border border-[#202938] bg-[#0d121a] p-5"><div className="text-xs uppercase tracking-wider text-[#718096]">Transparent build ledger</div><div className="mt-4 space-y-3 text-sm">{[['Audit fee','₹99.00'],['Base compute / tokens',`₹${(audit.computePaise/100).toFixed(2)}`],['Platform margin (10%)',`₹${(audit.marginPaise/100).toFixed(2)}`]].map(([a,b])=><div key={a} className="flex justify-between border-b border-[#202938] pb-3"><span className="text-[#7f8da3]">{a}</span><span>{b}</span></div>)}</div></div></div>
 </main>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-4 rounded-3xl border border-[#202938] bg-[#0d121a] p-7"><h2 className="text-2xl font-semibold">{title}</h2><div className="mt-5">{children}</div></section>}
function Mini({title,text,items}:{title:string;text?:string;items?:string[]}){return <div className="rounded-2xl border border-[#202938] bg-[#0a0f16] p-5"><div className="text-xs uppercase tracking-wider text-[#718096]">{title}</div>{text&&<p className="mt-3 text-sm leading-6 text-[#c0c8d5]">{text}</p>}{items&&<ul className="mt-3 space-y-2 text-sm leading-6 text-[#c0c8d5]">{items.map(x=><li key={x}>• {x}</li>)}</ul>}</div>}
function InfoCard({icon,title,text,items}:{icon:React.ReactNode;title:string;text?:string;items?:string[]}){return <div className="rounded-2xl border border-[#202938] bg-[#0d121a] p-5"><div className="flex items-center gap-2 text-[#77e2c1]">{icon}<span className="text-xs font-semibold uppercase tracking-wider">{title}</span></div>{text&&<p className="mt-3 text-sm leading-6 text-[#c0c8d5]">{text}</p>}{items&&<ul className="mt-3 space-y-2 text-sm leading-6 text-[#c0c8d5]">{items.map(x=><li key={x}>• {x}</li>)}</ul>}</div>}
