// Aristotle · "HOW COULD WE ACTUALLY ACHIEVE THIS?"
// Generates 3–5 materially different pathways to the founder's FULL objective (alternatives, never ranked), grounded in
// research (direct and analogous findings) and founder facts. Generated by the audit job itself, so a completed report
// always has them.
// Aristotle may challenge assumptions, but never shrinks the founder's ambition without evidence.
import type { AuditReport } from '../audit';
import type { ResearchRecord } from '../evidence';
import { buildFounderFactsBlock, type FounderFact } from '../founder-facts';
import { researchBrief } from '../research';
import { identityBlock, NOT_ESTABLISHED, PATHWAY_LENSES, type Pathway, type PathwayLens, type PathwaysResult, type Understanding } from './types';

export const PATHWAYS_SCHEMA = {
  type: 'object',
  properties: {
    goal: { type: 'string' },
    ambitionNote: { type: 'string' },
    pathways: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          name: { type: 'string' }, lens: { type: 'string', enum: [...PATHWAY_LENSES] },
          model: { type: 'string' }, customer: { type: 'string' }, valueProposition: { type: 'string' }, revenueMechanism: { type: 'string' },
          whyPlausible: { type: 'string' },
          evidence: { type: 'array', items: { type: 'object', properties: { statement: { type: 'string' }, refs: { type: 'array', items: { type: 'string' } } }, required: ['statement', 'refs'] } },
          assumptions: { type: 'array', items: { type: 'string' } },
          economics: { type: 'string' }, constraints: { type: 'array', items: { type: 'string' } }, risks: { type: 'array', items: { type: 'string' } },
          firstExperiment: { type: 'string' }, contributionToTarget: { type: 'string' },
        },
        required: ['name', 'lens', 'model', 'customer', 'valueProposition', 'revenueMechanism', 'whyPlausible', 'evidence', 'assumptions', 'economics', 'constraints', 'risks', 'firstExperiment', 'contributionToTarget'],
      },
    },
    combination: { type: 'string' },
    founderChecklist: { type: 'array', items: { type: 'string' } },
  },
  required: ['goal', 'ambitionNote', 'pathways', 'combination', 'founderChecklist'],
};

const LENS_GUIDE: Record<PathwayLens, string> = {
  OBVIOUS_ROUTE: 'the straightforward way most founders would do this',
  ADJACENT_ROUTE: 'a neighbouring customer, product or segment reached with the same capability',
  INTERNATIONAL_ANALOGUE: 'a model proven in another country, adapted to India (cite the ANALOGOUS finding if one exists)',
  CROSS_INDUSTRY_TRANSFER: 'a mechanism that works in another industry, transferred here',
  BUSINESS_MODEL_INVERSION: 'flip who pays, what is sold, or when money changes hands',
  DISTRIBUTION_ARBITRAGE: 'an under-priced or overlooked channel to the same customer',
  AI_TECHNOLOGY_LEVERAGE: 'AI / automation that changes the cost or reach of the model',
  ASSET_LIGHT: 'the version that needs the least capital, licence or inventory (partner, white-label, marketplace)',
  UNUSUAL_PLAUSIBLE: 'a less obvious route that the evidence still makes plausible',
  FOUNDER_SPECIFIC: 'a route that uses what THIS founder already has (stated facts, current business, assets)',
};

export function pathwaysPrompt(input: { objective: string; understanding: Understanding | null; facts: FounderFact[]; research: ResearchRecord | null; report: AuditReport; company?: string | null }): string {
  const memo = input.report.decisionMemo;
  return `You are Aristotle, the strategy capability of Hippoturtle. The founder's objective is NOT up for negotiation.
${identityBlock(input.company ?? null)}
Your job: lay out materially different pathways to achieve the FULL objective, as alternatives for the founder to choose between.

FOUNDER OBJECTIVE (verbatim): """${input.objective}"""
Target: ${input.understanding?.target || 'Not stated'} | Current state: ${input.understanding?.currentState || 'Not stated'}

${buildFounderFactsBlock(input.facts)}

${input.research ? researchBrief(input.research) : 'RESEARCH BRIEF: none available.'}

DECISION MEMO SO FAR:
Verdict: ${input.report.oneLineVerdict || input.report.verdict || ''}
Decision question: ${memo?.decisionQuestion || ''}
Critical assumptions: ${(memo?.criticalAssumptions || []).map((a) => `${a.assumption} [${a.evidenceStatus}]`).join(' | ')}

LENSES (consider all, then choose the 3–5 most relevant to THIS business — not random ideas):
${PATHWAY_LENSES.map((l) => `- ${l}: ${LENS_GUIDE[l]}`).join('\n')}

RULES (strict):
1. Produce 3–5 pathways, each from a DIFFERENT lens, materially different in customer, model, channel or who pays.
   Specific to this business in India. Do NOT rank them and never call one best or worst: they are alternatives.
2. Each pathway: model (how the business works on this pathway), customer, valueProposition, revenueMechanism
   (who pays whom, for what, when), whyPlausible, evidence, assumptions (what must be true, plainly stated), risks,
   firstExperiment, economics, constraints, contributionToTarget.
3. NEVER tell the founder to lower the target. If evidence suggests it is hard, say what would have to be true to reach it.
4. evidence: only statements supported by the research brief or founder facts. refs must be R# finding ids or F# founder
   fact ids from above. An ANALOGOUS finding may support a pathway only with the analogy stated in the statement.
   If nothing supports a pathway, return an empty evidence list — do NOT invent support.
5. economics: use numbers ONLY from F# facts or R# findings and cite them in brackets like [F1] [R2]. If unknown,
   write "${NOT_ESTABLISHED}" and say what must be measured.
6. contributionToTarget: phrase as a REQUIREMENT, never a forecast.
7. firstExperiment: the cheapest test (≤ 2 weeks) with a pass threshold that would show whether this pathway works.
8. No invented market sizes, statistics, prices or competitor names that are not in the research brief.
9. combination: how 2–3 pathways could combine to reach the full target, as requirements.
10. founderChecklist: 5–8 decisions only the founder can make (budget, risk appetite, channels to try first, working capital, hiring).
11. goal: the founder's objective in one line, unchanged. ambitionNote: one honest sentence on what reaching it demands.
Simple English. Return JSON only.`;
}

const REF = /^(R|F)\d+$/;

/**
 * Deterministic grounding: refs must exist; unsupported numbers in economics are replaced with "Not yet established.";
 * one pathway per lens; at least three pathways (a completed Deep Intelligence report always offers real alternatives).
 * `analogous`: R# findings that are only analogues (they inform a pathway; they do not make it SUPPORTED).
 */
export function normalisePathways(raw: unknown, valid: { findings: Set<string>; facts: Set<string>; analogous?: Set<string> }): PathwaysResult {
  const r = (raw || {}) as Record<string, unknown>;
  const str = (v: unknown, max = 1200) => (typeof v === 'string' ? v.trim().slice(0, max) : '');
  const arr = (v: unknown, n = 8) => (Array.isArray(v) ? v.map((x) => str(x, 400)).filter(Boolean).slice(0, n) : []);
  const ok = (ref: string) => REF.test(ref) && (ref.startsWith('R') ? valid.findings.has(ref) : valid.facts.has(ref));
  const kindOf = (refs: string[]): 'DIRECT' | 'ANALOGOUS' | 'FOUNDER' => (refs.some((x) => x.startsWith('R') && !valid.analogous?.has(x)) ? 'DIRECT' : refs.some((x) => x.startsWith('R')) ? 'ANALOGOUS' : 'FOUNDER');
  const lenses = new Set<string>();
  const pathways: Pathway[] = (Array.isArray(r.pathways) ? r.pathways : []).map((p: Record<string, unknown>) => {
    const evidence = (Array.isArray(p.evidence) ? p.evidence : [])
      .map((e: Record<string, unknown>) => ({ statement: str(e?.statement, 400), refs: (Array.isArray(e?.refs) ? e.refs : []).map(String).filter(ok) }))
      .filter((e: { statement: string; refs: string[] }) => e.statement && e.refs.length > 0)
      .map((e: { statement: string; refs: string[] }) => ({ ...e, kind: kindOf(e.refs) }));
    let economics = str(p.economics, 800) || NOT_ESTABLISHED;
    const cited = (economics.match(/\b[RF]\d+\b/g) || []).filter(ok);
    const withoutRefs = economics.replace(/\[?\b[RF]\d+\b\]?/g, '');
    if (/\d/.test(withoutRefs) && cited.length === 0) economics = `${NOT_ESTABLISHED} The figures proposed were not supported by your numbers or by research, so they were removed.`;
    const lens = PATHWAY_LENSES.includes(p.lens as PathwayLens) ? (p.lens as PathwayLens) : undefined;
    const model = str(p.model) || str(p.howItWorks);
    const grounded = evidence.filter((e) => e.kind !== 'ANALOGOUS').length;
    return {
      id: '', name: str(p.name, 120), ...(lens ? { lens } : {}), model,
      customer: str(p.customer, 300), valueProposition: str(p.valueProposition, 500), revenueMechanism: str(p.revenueMechanism, 400), assumptions: arr(p.assumptions, 6),
      howItWorks: model, whyPlausible: str(p.whyPlausible),
      evidence, economics, constraints: arr(p.constraints, 6), risks: arr(p.risks, 6), firstExperiment: str(p.firstExperiment, 600) || NOT_ESTABLISHED,
      contributionToTarget: str(p.contributionToTarget, 600) || NOT_ESTABLISHED,
      evidenceStrength: grounded >= 2 ? 'SUPPORTED' : grounded === 1 ? 'PARTIAL' : evidence.length ? 'ANALOGOUS' : 'NOT_YET_ESTABLISHED',
    } satisfies Pathway;
  }).filter((p) => p.howItWorks && (!p.lens || (!lenses.has(p.lens) && (lenses.add(p.lens), true)))) // materially different: one per lens
    .slice(0, 5)
    .map((p, i) => ({ ...p, id: `P${i + 1}`, name: p.name || `Pathway ${i + 1}` }));
  if (pathways.length < MIN_PATHWAYS) throw new Error(`PATHWAYS_INVALID: ${pathways.length} usable pathways were produced; at least ${MIN_PATHWAYS} materially different ones are required`);
  return { goal: str(r.goal, 400), ambitionNote: str(r.ambitionNote, 600), pathways, combination: str(r.combination, 1200), founderChecklist: arr(r.founderChecklist, 10) };
}
export const MIN_PATHWAYS = 3;

/** Grounding sets for normalisePathways from research + founder facts. */
export const pathwayRefs = (research: ResearchRecord | null, facts: { id: string }[]) => ({
  findings: new Set((research?.findings || []).map((f) => f.id)),
  facts: new Set(facts.map((f) => f.id)),
  analogous: new Set((research?.findings || []).filter((f) => f.evidenceType === 'ANALOGOUS').map((f) => f.id)),
});
